### ISSUE TITLE
Peer review - Milestone 3 - JMeter 

### ISSUE THREAD

**Issue by uteerna** [airavata-courses/ABC#127]
I cannot see the JMeter results for the instances. Can you please update those results?
Thanks.

**Comment by bhushanmalgaonkar** [comment]
Hi @uteerna 

We have now uploaded the results on the wiki. You can find them [here](https://github.com/airavata-courses/ABC/wiki/Performance-metrics-(Jmeter))

**Comment by uteerna** [comment]
Okay. I see it now. Thanks @bhushanmalgaonkar
