### ISSUE TITLE
Peer review - Milestone 3 - Chaos/Kube Monkey

### ISSUE THREAD

**Issue by uteerna** [airavata-courses/ABC#129]
I cannot find any implementation for Chaos/Kube Monkey. Can you please verify and let me know. Although when I checked manually the creation and deletion of the pods is happening with Kubernetes.

**Comment by chetan253** [comment]
Have you tried stopping the instance of service? As I can see all the services are currently running based on what replicas were defined for them. 

Kindly post your review prior and after results of your review, so we can evaluate this issue further

-Chetan

**Comment by uteerna** [comment]
I deleted one of the pods manually and Kubernetes created the pod before deleting the old pod. I was however looking for Chaos Monkey implementation as per the requirements of the milestone.

**Comment by uteerna** [comment]
Hi,
I just realized that Kube Monkey was optional. However, if you want to try it is worth the effort. Closing this. 
Thanks.
