### ISSUE TITLE
Installation issues

### ISSUE THREAD

**Issue by harishmaruthi** [airavata-courses/ABC#38]
Mac user.
1. 
 At step:  java -jar ABC/FeedService/target/feedservice-*.jar
Relative path doesn't match. Neophytes may face issues

2. At Step: Once you have npm installed, install react as follows:
npm install -g create-react-app
What is the need of this?

3. 
At DB startup--- Press Config in front of Apache and open httpd.conf
Change Listen 80 to Listen 8080
Here, 8080 is not feasible as Spring application by now would have taken the port.

4. Could not start the MySql DB server . Failed

**Comment by chetan253** [comment]
1. There is a note mentioned below that step what might be  an alternative

4. Are you using the MySQL DB directly or through xampp server? Is this point in anyway relates to #40 ?

**Comment by absheth** [comment]
For 2) This was included in wiki when we were setting up the project. We realized later on that it is not required once the app is created and package.json is ready. We forgot to removed that but wiki is now updated.

**Comment by harishmaruthi** [comment]
2=>. using the MySQL DB through xampp server. Apache starts on 9000 (issue with 80, 8080 would be occupied by one of our services) but DB server fails to start. Not sure what the error is.

**Comment by bhushanmalgaonkar** [comment]
@harishmaruthi 
2=> There is no need to start Apache service now. (Refer the updated wiki) You can directly connect to MySQL server. If you already have some MySQL database installed, you can use that. If not, you can use xampp. 
Once you start the database service, 
1. Create a database with name "node_mysql". 
2. Update config/connection.json in user-management-service. Check if port, username and password are correct.
3. Start the user-managent-service.

**Comment by absheth** [comment]
Harish, 

I believe there was a lot of confusion about installation. Considering that, we have updated the wiki and we would like you to do a clean installation in order to avoid any further confusion.

We believe you should not face any other installation issue and everything should run smoothly.
