### ISSUE TITLE
Npm Start Failure 

### ISSUE THREAD

**Issue by thumblas** [airavata-courses/ABC#45]
![screenshot from 2019-02-09 14-00-27](https://user-images.githubusercontent.com/9990210/52525133-24192680-2c73-11e9-821d-c5c851f5e554.png)

Npm start failing after I clone the User Management Service and I do npm start

**Comment by thumblas** [comment]
There is some issue in the db it seems

**Comment by bhushanmalgaonkar** [comment]
Make sure you have updated the connection.json file correctly (port and credentials) and you have a database with name "node_mysql".

**Comment by thumblas** [comment]
I added changes in the Connection.json file. Could you update the wiki with the node_mysql db step

**Comment by bhushanmalgaonkar** [comment]
It is already given in the wiki under MySQL server section. However, now I've updated it to specify all the values that are needed to be checked before starting the service.

Please close the issue if you think it's fixed.

**Comment by thumblas** [comment]
Hi,
The problem was because of the connection configurations in connection.json. Its starting fine. I am closing the issue
