### ISSUE TITLE
Python (Flask installation ) dependencies to be resolved

### ISSUE THREAD

**Issue by thumblas** [airavata-courses/ABC#46]
![screenshot from 2019-02-09 15-12-29](https://user-images.githubusercontent.com/9990210/52525813-28e2d800-2c7d-11e9-9fde-640ac13b5d48.png)

All the requirements seem to be installed. However, it doesn't seem to let me import. Might be version issue

**Comment by thumblas** [comment]
All the packages in the requirements.txt are installed. Please confirm on the versions since I tried uninstalling it and installing it again. I am not able to import it.
Python pip version - 2.7.12

**Comment by absheth** [comment]
Hi Shivani,

Did you start the virtualenv before installing dependencies from requirement.txt?

I ask this because I cannot see the virtualenv running.

**Comment by absheth** [comment]
Please start the virtual environment before installing the requirement.txt

Let us know if you face any issue.

**Comment by thumblas** [comment]
I just noticed. There was a issue on my side. I was trying without starting the flask_env virtual environment. Its working fine.
