### ISSUE TITLE
User Registration takes long time

### ISSUE THREAD

**Issue by thumblas** [airavata-courses/ABC#47]
![screenshot from 2019-02-10 00-17-50](https://user-images.githubusercontent.com/9990210/52529920-a0d6ef80-2cc9-11e9-8b21-9bba45559ceb.png)

**Comment by thumblas** [comment]
Is it because of the db sync issue [https://github.com/airavata-courses/ABC/issues/45](url)

**Comment by absheth** [comment]
It shouldn't take time. Can you check the terminal where user-management microservice is running and check if it is receiving any request? If yes, can you please share logs.

I am very sure it something related to configurations done during the setup.

**Comment by absheth** [comment]
Upon further investigation, I believe the error was because of ```web_ui/src/_actions/project.constant.js``` where the default URLs were changed. Please change all the hostnames to as below

```
export const USER_URL = 'http://localhost:3000'
export const FEED_URL = 'http://localhost:8080'
export const NEWS_URL = 'http://localhost:5000'
``` 

or you can just pull the latest commit.

Let us know if you face any issue.

**Comment by thumblas** [comment]
It is working fine after pulling the latest commits. I am closing this issue
