### ISSUE TITLE
Assignment 1 feedback

### ISSUE THREAD

**Issue by raghu2094** [airavata-courses/ABC#56]
Hey guys,
Are you maintaining a release branch for Project-1? I am starting with reviewing your project but couldn't find the release branch.

**Comment by chetan253** [comment]
Hi @raghu2094,

We are not maintaining the release branch as everything is there on develop branches. We decided to work on the forked repo's and hence there were no feature branches as well. You can find our final project outcome on develop branches directly. Wiki will help you to go through the installation process.

Apart from that if there are any issues, kindly let us know.

Thanks,
Chetan

**Comment by raghu2094** [comment]
@chetan253  Have you made any changes so far since project 1 to any of the branches? It would have been easy for us to grade if you had maintained a release branch.

**Comment by raghu2094** [comment]
@chetan253 Can you mail me the API key rtalwai@iu.edu

**Comment by chetan253** [comment]
> @chetan253 Have you made any changes so far since project 1 to any of the branches? It would have been easy for us to grade if you had maintained a release branch.

We didn't make any commits on any branches after project 1. Although we have on merge request open. We'll commit those changes after your evaluation.

> @chetan253 Can you mail me the API key [rtalwai@iu.edu](mailto:rtalwai@iu.edu)

I've mailed you the API key

**Comment by raghu2094** [comment]
Hi Team,
I have completed reviewing the project. I was able to start the project and run all the services without any issue. All services are in place and working fine. Apart from few issues like  same post being displayed twice which is a known issue I suppose, everything else worked smoothly. 
UI can be improved.
For assignment 1 it's fine if you start with few basic features but as we progress further into other assignments, we would like to see you build upon those features. I can see few functionalities in the pipeline and hopefully you would be implementing those in future assignments  
In the WIKI, Please remember to explain the purpose and working of each micro-service in brief. Rest all things have been mentioned properly except for the working.

Overall, good job so far and look forward to seeing more functionalities being added in your application.
All the best!

**Comment by raghu2094** [comment]
Also, it is better to have a release branch as you wouldn't need to be dependent on the graders to evaluate first before starting with the changes for the next assignment :)

**Comment by chetan253** [comment]
Thanks for your feedback @raghu2094. We will keep improving the project and introduce the functionalities as we go on. You made valid points and we will start working on them and make sure that they meet requirements in the next assignment.
